/*
 * Chatbot 聊天机器人 OpenAPI
 *
 * 聊天机器人 OpenAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package chatbot
// ChatReq struct for ChatReq
type ChatReq struct {
	// 图灵/小多
	ChannelId string `json:"channelId,omitempty"`
	// 输入类型:0-文本(默认)、1-图片、2-音频
	ReqType int32 `json:"reqType,omitempty"`
	Perception Perception `json:"perception,omitempty"`
	UserInfo UserInfo `json:"userInfo,omitempty"`
}
