/*
 * Chatbot 聊天机器人 OpenAPI
 *
 * 聊天机器人 OpenAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package chatbot
// Intent 请求意图
type Intent struct {
	// 输出功能code
	Code int32 `json:"code,omitempty"`
	// 意图名称
	IntentName string `json:"intentName,omitempty"`
	// 意图动作名称
	ActionName string `json:"actionName,omitempty"`
}
