/*
 * Chatbot 聊天机器人 OpenAPI
 *
 * 聊天机器人 OpenAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package chatbot
// Inspect struct for Inspect
type Inspect struct {
	Id string `json:"id,omitempty"`
	Question string `json:"question,omitempty"`
}
