/*
 * Chatbot 聊天机器人 OpenAPI
 *
 * 聊天机器人 OpenAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package chatbot
// SelfInfo 地理位置信息
type SelfInfo struct {
	Location Location `json:"location,omitempty"`
}
