/*
 * Chatbot 聊天机器人 OpenAPI
 *
 * 聊天机器人 OpenAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package chatbot
// InputImage 图片信息
type InputImage struct {
	Url string `json:"url,omitempty"`
}
