/*
 * Chatbot 聊天机器人 OpenAPI
 *
 * 聊天机器人 OpenAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package chatbot
// Location struct for Location
type Location struct {
	City string `json:"city,omitempty"`
	Province string `json:"province,omitempty"`
	Street string `json:"street,omitempty"`
}
