/*
 * Chatbot 聊天机器人 OpenAPI
 *
 * 聊天机器人 OpenAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package chatbot
// Perception 输入信息
type Perception struct {
	InputText InputText `json:"inputText,omitempty"`
	InputImage InputImage `json:"inputImage,omitempty"`
	InputMedia InputMedia `json:"inputMedia,omitempty"`
	SelfInfo SelfInfo `json:"selfInfo,omitempty"`
}
