/*
 * Chatbot 聊天机器人 OpenAPI
 *
 * 聊天机器人 OpenAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package chatbot
// InputMedia struct for InputMedia
type InputMedia struct {
	// 音频地址
	Url string `json:"url,omitempty"`
}
