/*
 * Chatbot 聊天机器人 OpenAPI
 *
 * 聊天机器人 OpenAPI
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package chatbot
// UserInfo 用户参数
type UserInfo struct {
	// 绑定的机器人标识
	BotId string `json:"botId,omitempty"`
	// 用户唯一标识
	UserId string `json:"userId,omitempty"`
	// 群聊唯一标识
	GroupId string `json:"groupId,omitempty"`
	// 群内用户昵称
	UserIdName string `json:"userIdName,omitempty"`
}
